#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PullToRefresh.Net.Example.Resource", IsApplication=true)]

namespace PullToRefresh.Net.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Handmark.PullToRefresh.Resource.Animation.slide_in_from_bottom = global::PullToRefresh.Net.Example.Resource.Animation.slide_in_from_bottom;
			global::Com.Handmark.PullToRefresh.Resource.Animation.slide_in_from_top = global::PullToRefresh.Net.Example.Resource.Animation.slide_in_from_top;
			global::Com.Handmark.PullToRefresh.Resource.Animation.slide_out_to_bottom = global::PullToRefresh.Net.Example.Resource.Animation.slide_out_to_bottom;
			global::Com.Handmark.PullToRefresh.Resource.Animation.slide_out_to_top = global::PullToRefresh.Net.Example.Resource.Animation.slide_out_to_top;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrAdapterViewBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrAdapterViewBackground;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrAnimationStyle = global::PullToRefresh.Net.Example.Resource.Attribute.ptrAnimationStyle;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrDrawable = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawable;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrDrawableBottom = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableBottom;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrDrawableEnd = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableEnd;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrDrawableStart = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableStart;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrDrawableTop = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableTop;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrHeaderBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderBackground;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrHeaderSubTextColor = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderSubTextColor;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderTextAppearance;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrHeaderTextColor = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderTextColor;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrListViewExtrasEnabled = global::PullToRefresh.Net.Example.Resource.Attribute.ptrListViewExtrasEnabled;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrMode = global::PullToRefresh.Net.Example.Resource.Attribute.ptrMode;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrOverScroll = global::PullToRefresh.Net.Example.Resource.Attribute.ptrOverScroll;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrRefreshableViewBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrRefreshableViewBackground;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrRotateDrawableWhilePulling = global::PullToRefresh.Net.Example.Resource.Attribute.ptrRotateDrawableWhilePulling;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrScrollingWhileRefreshingEnabled = global::PullToRefresh.Net.Example.Resource.Attribute.ptrScrollingWhileRefreshingEnabled;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrShowIndicator = global::PullToRefresh.Net.Example.Resource.Attribute.ptrShowIndicator;
			global::Com.Handmark.PullToRefresh.Resource.Attribute.ptrSubHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Attribute.ptrSubHeaderTextAppearance;
			global::Com.Handmark.PullToRefresh.Resource.Dimension.header_footer_left_right_padding = global::PullToRefresh.Net.Example.Resource.Dimension.header_footer_left_right_padding;
			global::Com.Handmark.PullToRefresh.Resource.Dimension.header_footer_top_bottom_padding = global::PullToRefresh.Net.Example.Resource.Dimension.header_footer_top_bottom_padding;
			global::Com.Handmark.PullToRefresh.Resource.Dimension.indicator_corner_radius = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_corner_radius;
			global::Com.Handmark.PullToRefresh.Resource.Dimension.indicator_internal_padding = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_internal_padding;
			global::Com.Handmark.PullToRefresh.Resource.Dimension.indicator_right_padding = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_right_padding;
			global::Com.Handmark.PullToRefresh.Resource.Drawable.default_ptr_flip = global::PullToRefresh.Net.Example.Resource.Drawable.default_ptr_flip;
			global::Com.Handmark.PullToRefresh.Resource.Drawable.default_ptr_rotate = global::PullToRefresh.Net.Example.Resource.Drawable.default_ptr_rotate;
			global::Com.Handmark.PullToRefresh.Resource.Drawable.indicator_arrow = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_arrow;
			global::Com.Handmark.PullToRefresh.Resource.Drawable.indicator_bg_bottom = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_bg_bottom;
			global::Com.Handmark.PullToRefresh.Resource.Drawable.indicator_bg_top = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_bg_top;
			global::Com.Handmark.PullToRefresh.Resource.Id.both = global::PullToRefresh.Net.Example.Resource.Id.both;
			global::Com.Handmark.PullToRefresh.Resource.Id.disabled = global::PullToRefresh.Net.Example.Resource.Id.disabled;
			global::Com.Handmark.PullToRefresh.Resource.Id.fl_inner = global::PullToRefresh.Net.Example.Resource.Id.fl_inner;
			global::Com.Handmark.PullToRefresh.Resource.Id.flip = global::PullToRefresh.Net.Example.Resource.Id.flip;
			global::Com.Handmark.PullToRefresh.Resource.Id.gridview = global::PullToRefresh.Net.Example.Resource.Id.gridview;
			global::Com.Handmark.PullToRefresh.Resource.Id.manualOnly = global::PullToRefresh.Net.Example.Resource.Id.manualOnly;
			global::Com.Handmark.PullToRefresh.Resource.Id.pullDownFromTop = global::PullToRefresh.Net.Example.Resource.Id.pullDownFromTop;
			global::Com.Handmark.PullToRefresh.Resource.Id.pullFromEnd = global::PullToRefresh.Net.Example.Resource.Id.pullFromEnd;
			global::Com.Handmark.PullToRefresh.Resource.Id.pullFromStart = global::PullToRefresh.Net.Example.Resource.Id.pullFromStart;
			global::Com.Handmark.PullToRefresh.Resource.Id.pullUpFromBottom = global::PullToRefresh.Net.Example.Resource.Id.pullUpFromBottom;
			global::Com.Handmark.PullToRefresh.Resource.Id.pull_to_refresh_image = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_image;
			global::Com.Handmark.PullToRefresh.Resource.Id.pull_to_refresh_progress = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_progress;
			global::Com.Handmark.PullToRefresh.Resource.Id.pull_to_refresh_sub_text = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_sub_text;
			global::Com.Handmark.PullToRefresh.Resource.Id.pull_to_refresh_text = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_text;
			global::Com.Handmark.PullToRefresh.Resource.Id.rotate = global::PullToRefresh.Net.Example.Resource.Id.rotate;
			global::Com.Handmark.PullToRefresh.Resource.Id.scrollview = global::PullToRefresh.Net.Example.Resource.Id.scrollview;
			global::Com.Handmark.PullToRefresh.Resource.Id.viewpager = global::PullToRefresh.Net.Example.Resource.Id.viewpager;
			global::Com.Handmark.PullToRefresh.Resource.Id.webview = global::PullToRefresh.Net.Example.Resource.Id.webview;
			global::Com.Handmark.PullToRefresh.Resource.Layout.pull_to_refresh_header_horizontal = global::PullToRefresh.Net.Example.Resource.Layout.pull_to_refresh_header_horizontal;
			global::Com.Handmark.PullToRefresh.Resource.Layout.pull_to_refresh_header_vertical = global::PullToRefresh.Net.Example.Resource.Layout.pull_to_refresh_header_vertical;
			global::Com.Handmark.PullToRefresh.Resource.String.pull_to_refresh_from_bottom_pull_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_pull_label;
			global::Com.Handmark.PullToRefresh.Resource.String.pull_to_refresh_from_bottom_refreshing_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_refreshing_label;
			global::Com.Handmark.PullToRefresh.Resource.String.pull_to_refresh_from_bottom_release_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_release_label;
			global::Com.Handmark.PullToRefresh.Resource.String.pull_to_refresh_pull_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_pull_label;
			global::Com.Handmark.PullToRefresh.Resource.String.pull_to_refresh_refreshing_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_refreshing_label;
			global::Com.Handmark.PullToRefresh.Resource.String.pull_to_refresh_release_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_release_label;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrAdapterViewBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrAdapterViewBackground;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrAnimationStyle = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrAnimationStyle;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrDrawable = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawable;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrDrawableBottom = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableBottom;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrDrawableEnd = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableEnd;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrDrawableStart = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableStart;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrDrawableTop = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableTop;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrHeaderBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderBackground;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrHeaderSubTextColor = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderSubTextColor;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderTextAppearance;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrHeaderTextColor = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderTextColor;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrListViewExtrasEnabled = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrListViewExtrasEnabled;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrMode = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrMode;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrOverScroll = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrOverScroll;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrRefreshableViewBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrRefreshableViewBackground;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrRotateDrawableWhilePulling = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrRotateDrawableWhilePulling;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrScrollingWhileRefreshingEnabled = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrScrollingWhileRefreshingEnabled;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrShowIndicator = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrShowIndicator;
			global::Com.Handmark.PullToRefresh.Resource.Styleable.PullToRefresh_ptrSubHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrSubHeaderTextAppearance;
			global::PullToRefresh.Net.ListFragment.Resource.Animation.slide_in_from_bottom = global::PullToRefresh.Net.Example.Resource.Animation.slide_in_from_bottom;
			global::PullToRefresh.Net.ListFragment.Resource.Animation.slide_in_from_top = global::PullToRefresh.Net.Example.Resource.Animation.slide_in_from_top;
			global::PullToRefresh.Net.ListFragment.Resource.Animation.slide_out_to_bottom = global::PullToRefresh.Net.Example.Resource.Animation.slide_out_to_bottom;
			global::PullToRefresh.Net.ListFragment.Resource.Animation.slide_out_to_top = global::PullToRefresh.Net.Example.Resource.Animation.slide_out_to_top;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrAdapterViewBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrAdapterViewBackground;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrAnimationStyle = global::PullToRefresh.Net.Example.Resource.Attribute.ptrAnimationStyle;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrDrawable = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawable;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrDrawableBottom = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableBottom;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrDrawableEnd = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableEnd;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrDrawableStart = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableStart;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrDrawableTop = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableTop;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrHeaderBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrHeaderSubTextColor = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderSubTextColor;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderTextAppearance;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrHeaderTextColor = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderTextColor;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrListViewExtrasEnabled = global::PullToRefresh.Net.Example.Resource.Attribute.ptrListViewExtrasEnabled;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrMode = global::PullToRefresh.Net.Example.Resource.Attribute.ptrMode;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrOverScroll = global::PullToRefresh.Net.Example.Resource.Attribute.ptrOverScroll;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrRefreshableViewBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrRefreshableViewBackground;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrRotateDrawableWhilePulling = global::PullToRefresh.Net.Example.Resource.Attribute.ptrRotateDrawableWhilePulling;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrScrollingWhileRefreshingEnabled = global::PullToRefresh.Net.Example.Resource.Attribute.ptrScrollingWhileRefreshingEnabled;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrShowIndicator = global::PullToRefresh.Net.Example.Resource.Attribute.ptrShowIndicator;
			global::PullToRefresh.Net.ListFragment.Resource.Attribute.ptrSubHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Attribute.ptrSubHeaderTextAppearance;
			global::PullToRefresh.Net.ListFragment.Resource.Dimension.header_footer_left_right_padding = global::PullToRefresh.Net.Example.Resource.Dimension.header_footer_left_right_padding;
			global::PullToRefresh.Net.ListFragment.Resource.Dimension.header_footer_top_bottom_padding = global::PullToRefresh.Net.Example.Resource.Dimension.header_footer_top_bottom_padding;
			global::PullToRefresh.Net.ListFragment.Resource.Dimension.indicator_corner_radius = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_corner_radius;
			global::PullToRefresh.Net.ListFragment.Resource.Dimension.indicator_internal_padding = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_internal_padding;
			global::PullToRefresh.Net.ListFragment.Resource.Dimension.indicator_right_padding = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_right_padding;
			global::PullToRefresh.Net.ListFragment.Resource.Drawable.default_ptr_flip = global::PullToRefresh.Net.Example.Resource.Drawable.default_ptr_flip;
			global::PullToRefresh.Net.ListFragment.Resource.Drawable.default_ptr_rotate = global::PullToRefresh.Net.Example.Resource.Drawable.default_ptr_rotate;
			global::PullToRefresh.Net.ListFragment.Resource.Drawable.indicator_arrow = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_arrow;
			global::PullToRefresh.Net.ListFragment.Resource.Drawable.indicator_bg_bottom = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_bg_bottom;
			global::PullToRefresh.Net.ListFragment.Resource.Drawable.indicator_bg_top = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_bg_top;
			global::PullToRefresh.Net.ListFragment.Resource.Id.both = global::PullToRefresh.Net.Example.Resource.Id.both;
			global::PullToRefresh.Net.ListFragment.Resource.Id.disabled = global::PullToRefresh.Net.Example.Resource.Id.disabled;
			global::PullToRefresh.Net.ListFragment.Resource.Id.fl_inner = global::PullToRefresh.Net.Example.Resource.Id.fl_inner;
			global::PullToRefresh.Net.ListFragment.Resource.Id.flip = global::PullToRefresh.Net.Example.Resource.Id.flip;
			global::PullToRefresh.Net.ListFragment.Resource.Id.gridview = global::PullToRefresh.Net.Example.Resource.Id.gridview;
			global::PullToRefresh.Net.ListFragment.Resource.Id.manualOnly = global::PullToRefresh.Net.Example.Resource.Id.manualOnly;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pullDownFromTop = global::PullToRefresh.Net.Example.Resource.Id.pullDownFromTop;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pullFromEnd = global::PullToRefresh.Net.Example.Resource.Id.pullFromEnd;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pullFromStart = global::PullToRefresh.Net.Example.Resource.Id.pullFromStart;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pullUpFromBottom = global::PullToRefresh.Net.Example.Resource.Id.pullUpFromBottom;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pull_to_refresh_image = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_image;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pull_to_refresh_progress = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_progress;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pull_to_refresh_sub_text = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_sub_text;
			global::PullToRefresh.Net.ListFragment.Resource.Id.pull_to_refresh_text = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_text;
			global::PullToRefresh.Net.ListFragment.Resource.Id.rotate = global::PullToRefresh.Net.Example.Resource.Id.rotate;
			global::PullToRefresh.Net.ListFragment.Resource.Id.scrollview = global::PullToRefresh.Net.Example.Resource.Id.scrollview;
			global::PullToRefresh.Net.ListFragment.Resource.Id.viewpager = global::PullToRefresh.Net.Example.Resource.Id.viewpager;
			global::PullToRefresh.Net.ListFragment.Resource.Id.webview = global::PullToRefresh.Net.Example.Resource.Id.webview;
			global::PullToRefresh.Net.ListFragment.Resource.Layout.pull_to_refresh_header_horizontal = global::PullToRefresh.Net.Example.Resource.Layout.pull_to_refresh_header_horizontal;
			global::PullToRefresh.Net.ListFragment.Resource.Layout.pull_to_refresh_header_vertical = global::PullToRefresh.Net.Example.Resource.Layout.pull_to_refresh_header_vertical;
			global::PullToRefresh.Net.ListFragment.Resource.String.ApplicationName = global::PullToRefresh.Net.Example.Resource.String.ApplicationName;
			global::PullToRefresh.Net.ListFragment.Resource.String.Hello = global::PullToRefresh.Net.Example.Resource.String.Hello;
			global::PullToRefresh.Net.ListFragment.Resource.String.pull_to_refresh_from_bottom_pull_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_pull_label;
			global::PullToRefresh.Net.ListFragment.Resource.String.pull_to_refresh_from_bottom_refreshing_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_refreshing_label;
			global::PullToRefresh.Net.ListFragment.Resource.String.pull_to_refresh_from_bottom_release_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_release_label;
			global::PullToRefresh.Net.ListFragment.Resource.String.pull_to_refresh_pull_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_pull_label;
			global::PullToRefresh.Net.ListFragment.Resource.String.pull_to_refresh_refreshing_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_refreshing_label;
			global::PullToRefresh.Net.ListFragment.Resource.String.pull_to_refresh_release_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_release_label;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrAdapterViewBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrAdapterViewBackground;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrAnimationStyle = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrAnimationStyle;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrDrawable = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawable;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrDrawableBottom = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableBottom;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrDrawableEnd = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableEnd;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrDrawableStart = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableStart;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrDrawableTop = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableTop;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrHeaderBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderBackground;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrHeaderSubTextColor = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderSubTextColor;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderTextAppearance;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrHeaderTextColor = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderTextColor;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrListViewExtrasEnabled = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrListViewExtrasEnabled;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrMode = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrMode;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrOverScroll = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrOverScroll;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrRefreshableViewBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrRefreshableViewBackground;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrRotateDrawableWhilePulling = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrRotateDrawableWhilePulling;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrScrollingWhileRefreshingEnabled = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrScrollingWhileRefreshingEnabled;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrShowIndicator = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrShowIndicator;
			global::PullToRefresh.Net.ListFragment.Resource.Styleable.PullToRefresh_ptrSubHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrSubHeaderTextAppearance;
			global::PullToRefresh.Net.Viewpager.Resource.Animation.slide_in_from_bottom = global::PullToRefresh.Net.Example.Resource.Animation.slide_in_from_bottom;
			global::PullToRefresh.Net.Viewpager.Resource.Animation.slide_in_from_top = global::PullToRefresh.Net.Example.Resource.Animation.slide_in_from_top;
			global::PullToRefresh.Net.Viewpager.Resource.Animation.slide_out_to_bottom = global::PullToRefresh.Net.Example.Resource.Animation.slide_out_to_bottom;
			global::PullToRefresh.Net.Viewpager.Resource.Animation.slide_out_to_top = global::PullToRefresh.Net.Example.Resource.Animation.slide_out_to_top;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrAdapterViewBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrAdapterViewBackground;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrAnimationStyle = global::PullToRefresh.Net.Example.Resource.Attribute.ptrAnimationStyle;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrDrawable = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawable;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrDrawableBottom = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableBottom;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrDrawableEnd = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableEnd;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrDrawableStart = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableStart;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrDrawableTop = global::PullToRefresh.Net.Example.Resource.Attribute.ptrDrawableTop;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrHeaderBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrHeaderSubTextColor = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderSubTextColor;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderTextAppearance;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrHeaderTextColor = global::PullToRefresh.Net.Example.Resource.Attribute.ptrHeaderTextColor;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrListViewExtrasEnabled = global::PullToRefresh.Net.Example.Resource.Attribute.ptrListViewExtrasEnabled;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrMode = global::PullToRefresh.Net.Example.Resource.Attribute.ptrMode;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrOverScroll = global::PullToRefresh.Net.Example.Resource.Attribute.ptrOverScroll;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrRefreshableViewBackground = global::PullToRefresh.Net.Example.Resource.Attribute.ptrRefreshableViewBackground;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrRotateDrawableWhilePulling = global::PullToRefresh.Net.Example.Resource.Attribute.ptrRotateDrawableWhilePulling;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrScrollingWhileRefreshingEnabled = global::PullToRefresh.Net.Example.Resource.Attribute.ptrScrollingWhileRefreshingEnabled;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrShowIndicator = global::PullToRefresh.Net.Example.Resource.Attribute.ptrShowIndicator;
			global::PullToRefresh.Net.Viewpager.Resource.Attribute.ptrSubHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Attribute.ptrSubHeaderTextAppearance;
			global::PullToRefresh.Net.Viewpager.Resource.Dimension.header_footer_left_right_padding = global::PullToRefresh.Net.Example.Resource.Dimension.header_footer_left_right_padding;
			global::PullToRefresh.Net.Viewpager.Resource.Dimension.header_footer_top_bottom_padding = global::PullToRefresh.Net.Example.Resource.Dimension.header_footer_top_bottom_padding;
			global::PullToRefresh.Net.Viewpager.Resource.Dimension.indicator_corner_radius = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_corner_radius;
			global::PullToRefresh.Net.Viewpager.Resource.Dimension.indicator_internal_padding = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_internal_padding;
			global::PullToRefresh.Net.Viewpager.Resource.Dimension.indicator_right_padding = global::PullToRefresh.Net.Example.Resource.Dimension.indicator_right_padding;
			global::PullToRefresh.Net.Viewpager.Resource.Drawable.default_ptr_flip = global::PullToRefresh.Net.Example.Resource.Drawable.default_ptr_flip;
			global::PullToRefresh.Net.Viewpager.Resource.Drawable.default_ptr_rotate = global::PullToRefresh.Net.Example.Resource.Drawable.default_ptr_rotate;
			global::PullToRefresh.Net.Viewpager.Resource.Drawable.indicator_arrow = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_arrow;
			global::PullToRefresh.Net.Viewpager.Resource.Drawable.indicator_bg_bottom = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_bg_bottom;
			global::PullToRefresh.Net.Viewpager.Resource.Drawable.indicator_bg_top = global::PullToRefresh.Net.Example.Resource.Drawable.indicator_bg_top;
			global::PullToRefresh.Net.Viewpager.Resource.Id.both = global::PullToRefresh.Net.Example.Resource.Id.both;
			global::PullToRefresh.Net.Viewpager.Resource.Id.disabled = global::PullToRefresh.Net.Example.Resource.Id.disabled;
			global::PullToRefresh.Net.Viewpager.Resource.Id.fl_inner = global::PullToRefresh.Net.Example.Resource.Id.fl_inner;
			global::PullToRefresh.Net.Viewpager.Resource.Id.flip = global::PullToRefresh.Net.Example.Resource.Id.flip;
			global::PullToRefresh.Net.Viewpager.Resource.Id.gridview = global::PullToRefresh.Net.Example.Resource.Id.gridview;
			global::PullToRefresh.Net.Viewpager.Resource.Id.manualOnly = global::PullToRefresh.Net.Example.Resource.Id.manualOnly;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pullDownFromTop = global::PullToRefresh.Net.Example.Resource.Id.pullDownFromTop;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pullFromEnd = global::PullToRefresh.Net.Example.Resource.Id.pullFromEnd;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pullFromStart = global::PullToRefresh.Net.Example.Resource.Id.pullFromStart;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pullUpFromBottom = global::PullToRefresh.Net.Example.Resource.Id.pullUpFromBottom;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pull_to_refresh_image = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_image;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pull_to_refresh_progress = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_progress;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pull_to_refresh_sub_text = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_sub_text;
			global::PullToRefresh.Net.Viewpager.Resource.Id.pull_to_refresh_text = global::PullToRefresh.Net.Example.Resource.Id.pull_to_refresh_text;
			global::PullToRefresh.Net.Viewpager.Resource.Id.rotate = global::PullToRefresh.Net.Example.Resource.Id.rotate;
			global::PullToRefresh.Net.Viewpager.Resource.Id.scrollview = global::PullToRefresh.Net.Example.Resource.Id.scrollview;
			global::PullToRefresh.Net.Viewpager.Resource.Id.viewpager = global::PullToRefresh.Net.Example.Resource.Id.viewpager;
			global::PullToRefresh.Net.Viewpager.Resource.Id.webview = global::PullToRefresh.Net.Example.Resource.Id.webview;
			global::PullToRefresh.Net.Viewpager.Resource.Layout.pull_to_refresh_header_horizontal = global::PullToRefresh.Net.Example.Resource.Layout.pull_to_refresh_header_horizontal;
			global::PullToRefresh.Net.Viewpager.Resource.Layout.pull_to_refresh_header_vertical = global::PullToRefresh.Net.Example.Resource.Layout.pull_to_refresh_header_vertical;
			global::PullToRefresh.Net.Viewpager.Resource.String.ApplicationName = global::PullToRefresh.Net.Example.Resource.String.ApplicationName;
			global::PullToRefresh.Net.Viewpager.Resource.String.Hello = global::PullToRefresh.Net.Example.Resource.String.Hello;
			global::PullToRefresh.Net.Viewpager.Resource.String.pull_to_refresh_from_bottom_pull_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_pull_label;
			global::PullToRefresh.Net.Viewpager.Resource.String.pull_to_refresh_from_bottom_refreshing_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_refreshing_label;
			global::PullToRefresh.Net.Viewpager.Resource.String.pull_to_refresh_from_bottom_release_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_from_bottom_release_label;
			global::PullToRefresh.Net.Viewpager.Resource.String.pull_to_refresh_pull_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_pull_label;
			global::PullToRefresh.Net.Viewpager.Resource.String.pull_to_refresh_refreshing_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_refreshing_label;
			global::PullToRefresh.Net.Viewpager.Resource.String.pull_to_refresh_release_label = global::PullToRefresh.Net.Example.Resource.String.pull_to_refresh_release_label;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrAdapterViewBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrAdapterViewBackground;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrAnimationStyle = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrAnimationStyle;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrDrawable = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawable;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrDrawableBottom = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableBottom;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrDrawableEnd = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableEnd;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrDrawableStart = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableStart;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrDrawableTop = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrDrawableTop;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrHeaderBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderBackground;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrHeaderSubTextColor = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderSubTextColor;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderTextAppearance;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrHeaderTextColor = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrHeaderTextColor;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrListViewExtrasEnabled = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrListViewExtrasEnabled;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrMode = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrMode;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrOverScroll = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrOverScroll;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrRefreshableViewBackground = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrRefreshableViewBackground;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrRotateDrawableWhilePulling = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrRotateDrawableWhilePulling;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrScrollingWhileRefreshingEnabled = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrScrollingWhileRefreshingEnabled;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrShowIndicator = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrShowIndicator;
			global::PullToRefresh.Net.Viewpager.Resource.Styleable.PullToRefresh_ptrSubHeaderTextAppearance = global::PullToRefresh.Net.Example.Resource.Styleable.PullToRefresh_ptrSubHeaderTextAppearance;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_from_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_from_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_to_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_to_top = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ptrAdapterViewBackground = 2130771984;
			
			// aapt resource value: 0x7f01000c
			public const int ptrAnimationStyle = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int ptrDrawable = 2130771974;
			
			// aapt resource value: 0x7f010012
			public const int ptrDrawableBottom = 2130771986;
			
			// aapt resource value: 0x7f010008
			public const int ptrDrawableEnd = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ptrDrawableStart = 2130771975;
			
			// aapt resource value: 0x7f010011
			public const int ptrDrawableTop = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int ptrHeaderBackground = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int ptrHeaderSubTextColor = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int ptrHeaderTextAppearance = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int ptrHeaderTextColor = 2130771970;
			
			// aapt resource value: 0x7f01000e
			public const int ptrListViewExtrasEnabled = 2130771982;
			
			// aapt resource value: 0x7f010004
			public const int ptrMode = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int ptrOverScroll = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int ptrRefreshableViewBackground = 2130771968;
			
			// aapt resource value: 0x7f01000f
			public const int ptrRotateDrawableWhilePulling = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int ptrScrollingWhileRefreshingEnabled = 2130771981;
			
			// aapt resource value: 0x7f010005
			public const int ptrShowIndicator = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int ptrSubHeaderTextAppearance = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080003
			public const int header_footer_left_right_padding = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int header_footer_top_bottom_padding = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int indicator_corner_radius = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int indicator_internal_padding = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int indicator_right_padding = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_ptr_flip = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int default_ptr_rotate = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int indicator_arrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int indicator_bg_bottom = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int indicator_bg_top = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int wallpaper = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int MyButton = 2131165207;
			
			// aapt resource value: 0x7f070003
			public const int both = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int disabled = 2131165184;
			
			// aapt resource value: 0x7f070018
			public const int fl_inner = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int flip = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int frag_ptr_list = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int gridview = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int manualOnly = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int pullDownFromTop = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int pullFromEnd = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int pullFromStart = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int pullUpFromBottom = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int pull_refresh_expandable_list = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int pull_refresh_grid = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int pull_refresh_horizontalscrollview = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int pull_refresh_list = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int pull_refresh_scrollview = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int pull_refresh_viewpager = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int pull_refresh_webview = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int pull_refresh_webview2 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int pull_to_refresh_image = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int pull_to_refresh_progress = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int pull_to_refresh_sub_text = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int pull_to_refresh_text = 2131165211;
			
			// aapt resource value: 0x7f070007
			public const int rotate = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int scrollview = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int viewpager = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int vp_list = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int webview = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_ptr_expandable_list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_ptr_grid = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_ptr_horizontalscrollview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_ptr_list = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_ptr_list_fragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_ptr_list_in_vp = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_ptr_scrollview = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_ptr_viewpager = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_ptr_webview = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_ptr_webview2 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int layout_listview_in_viewpager = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int pull_to_refresh_header_horizontal = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int pull_to_refresh_header_vertical = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int pull_event = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int refreshing_sound = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int reset_sound = 2131034114;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int applicationname = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int filler_text = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int pull_to_refresh_from_bottom_pull_label = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int pull_to_refresh_from_bottom_refreshing_label = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int pull_to_refresh_from_bottom_release_label = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int pull_to_refresh_pull_label = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int pull_to_refresh_refreshing_label = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int pull_to_refresh_release_label = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int HorizScrollViewItem = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresh = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 16
			public const int PullToRefresh_ptrAdapterViewBackground = 16;
			
			// aapt resource value: 12
			public const int PullToRefresh_ptrAnimationStyle = 12;
			
			// aapt resource value: 6
			public const int PullToRefresh_ptrDrawable = 6;
			
			// aapt resource value: 18
			public const int PullToRefresh_ptrDrawableBottom = 18;
			
			// aapt resource value: 8
			public const int PullToRefresh_ptrDrawableEnd = 8;
			
			// aapt resource value: 7
			public const int PullToRefresh_ptrDrawableStart = 7;
			
			// aapt resource value: 17
			public const int PullToRefresh_ptrDrawableTop = 17;
			
			// aapt resource value: 1
			public const int PullToRefresh_ptrHeaderBackground = 1;
			
			// aapt resource value: 3
			public const int PullToRefresh_ptrHeaderSubTextColor = 3;
			
			// aapt resource value: 10
			public const int PullToRefresh_ptrHeaderTextAppearance = 10;
			
			// aapt resource value: 2
			public const int PullToRefresh_ptrHeaderTextColor = 2;
			
			// aapt resource value: 14
			public const int PullToRefresh_ptrListViewExtrasEnabled = 14;
			
			// aapt resource value: 4
			public const int PullToRefresh_ptrMode = 4;
			
			// aapt resource value: 9
			public const int PullToRefresh_ptrOverScroll = 9;
			
			// aapt resource value: 0
			public const int PullToRefresh_ptrRefreshableViewBackground = 0;
			
			// aapt resource value: 15
			public const int PullToRefresh_ptrRotateDrawableWhilePulling = 15;
			
			// aapt resource value: 13
			public const int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 13;
			
			// aapt resource value: 5
			public const int PullToRefresh_ptrShowIndicator = 5;
			
			// aapt resource value: 11
			public const int PullToRefresh_ptrSubHeaderTextAppearance = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
