#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PullToRefresh.Net.ListFragment.Resource", IsApplication=false)]

namespace PullToRefresh.Net.ListFragment
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int slide_in_from_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int slide_in_from_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int slide_out_to_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int slide_out_to_top = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public static int ptrAdapterViewBackground = 2130771984;
			
			// aapt resource value: 0x7f01000c
			public static int ptrAnimationStyle = 2130771980;
			
			// aapt resource value: 0x7f010006
			public static int ptrDrawable = 2130771974;
			
			// aapt resource value: 0x7f010012
			public static int ptrDrawableBottom = 2130771986;
			
			// aapt resource value: 0x7f010008
			public static int ptrDrawableEnd = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int ptrDrawableStart = 2130771975;
			
			// aapt resource value: 0x7f010011
			public static int ptrDrawableTop = 2130771985;
			
			// aapt resource value: 0x7f010001
			public static int ptrHeaderBackground = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int ptrHeaderSubTextColor = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public static int ptrHeaderTextAppearance = 2130771978;
			
			// aapt resource value: 0x7f010002
			public static int ptrHeaderTextColor = 2130771970;
			
			// aapt resource value: 0x7f01000e
			public static int ptrListViewExtrasEnabled = 2130771982;
			
			// aapt resource value: 0x7f010004
			public static int ptrMode = 2130771972;
			
			// aapt resource value: 0x7f010009
			public static int ptrOverScroll = 2130771977;
			
			// aapt resource value: 0x7f010000
			public static int ptrRefreshableViewBackground = 2130771968;
			
			// aapt resource value: 0x7f01000f
			public static int ptrRotateDrawableWhilePulling = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public static int ptrScrollingWhileRefreshingEnabled = 2130771981;
			
			// aapt resource value: 0x7f010005
			public static int ptrShowIndicator = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public static int ptrSubHeaderTextAppearance = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public static int header_footer_left_right_padding = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int header_footer_top_bottom_padding = 2131099652;
			
			// aapt resource value: 0x7f060001
			public static int indicator_corner_radius = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int indicator_internal_padding = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int indicator_right_padding = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int default_ptr_flip = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int default_ptr_rotate = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int indicator_arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int indicator_bg_bottom = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int indicator_bg_top = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public static int both = 2131034115;
			
			// aapt resource value: 0x7f050000
			public static int disabled = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public static int fl_inner = 2131034125;
			
			// aapt resource value: 0x7f050008
			public static int flip = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int gridview = 2131034121;
			
			// aapt resource value: 0x7f050004
			public static int manualOnly = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int pullDownFromTop = 2131034117;
			
			// aapt resource value: 0x7f050002
			public static int pullFromEnd = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int pullFromStart = 2131034113;
			
			// aapt resource value: 0x7f050006
			public static int pullUpFromBottom = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public static int pull_to_refresh_image = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public static int pull_to_refresh_progress = 2131034127;
			
			// aapt resource value: 0x7f050011
			public static int pull_to_refresh_sub_text = 2131034129;
			
			// aapt resource value: 0x7f050010
			public static int pull_to_refresh_text = 2131034128;
			
			// aapt resource value: 0x7f050007
			public static int rotate = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public static int scrollview = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public static int viewpager = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public static int webview = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int pull_to_refresh_header_horizontal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int pull_to_refresh_header_vertical = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070007
			public static int ApplicationName = 2131165191;
			
			// aapt resource value: 0x7f070006
			public static int Hello = 2131165190;
			
			// aapt resource value: 0x7f070003
			public static int pull_to_refresh_from_bottom_pull_label = 2131165187;
			
			// aapt resource value: 0x7f070005
			public static int pull_to_refresh_from_bottom_refreshing_label = 2131165189;
			
			// aapt resource value: 0x7f070004
			public static int pull_to_refresh_from_bottom_release_label = 2131165188;
			
			// aapt resource value: 0x7f070000
			public static int pull_to_refresh_pull_label = 2131165184;
			
			// aapt resource value: 0x7f070002
			public static int pull_to_refresh_refreshing_label = 2131165186;
			
			// aapt resource value: 0x7f070001
			public static int pull_to_refresh_release_label = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresh = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 16
			public static int PullToRefresh_ptrAdapterViewBackground = 16;
			
			// aapt resource value: 12
			public static int PullToRefresh_ptrAnimationStyle = 12;
			
			// aapt resource value: 6
			public static int PullToRefresh_ptrDrawable = 6;
			
			// aapt resource value: 18
			public static int PullToRefresh_ptrDrawableBottom = 18;
			
			// aapt resource value: 8
			public static int PullToRefresh_ptrDrawableEnd = 8;
			
			// aapt resource value: 7
			public static int PullToRefresh_ptrDrawableStart = 7;
			
			// aapt resource value: 17
			public static int PullToRefresh_ptrDrawableTop = 17;
			
			// aapt resource value: 1
			public static int PullToRefresh_ptrHeaderBackground = 1;
			
			// aapt resource value: 3
			public static int PullToRefresh_ptrHeaderSubTextColor = 3;
			
			// aapt resource value: 10
			public static int PullToRefresh_ptrHeaderTextAppearance = 10;
			
			// aapt resource value: 2
			public static int PullToRefresh_ptrHeaderTextColor = 2;
			
			// aapt resource value: 14
			public static int PullToRefresh_ptrListViewExtrasEnabled = 14;
			
			// aapt resource value: 4
			public static int PullToRefresh_ptrMode = 4;
			
			// aapt resource value: 9
			public static int PullToRefresh_ptrOverScroll = 9;
			
			// aapt resource value: 0
			public static int PullToRefresh_ptrRefreshableViewBackground = 0;
			
			// aapt resource value: 15
			public static int PullToRefresh_ptrRotateDrawableWhilePulling = 15;
			
			// aapt resource value: 13
			public static int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 13;
			
			// aapt resource value: 5
			public static int PullToRefresh_ptrShowIndicator = 5;
			
			// aapt resource value: 11
			public static int PullToRefresh_ptrSubHeaderTextAppearance = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
